// FIX: Import GenerateContentResponse for proper typing.
import { GoogleGenAI, Modality, GenerateContentResponse } from "@google/genai";
import { AspectRatio } from '../types';

// FIX: Initialize GoogleGenAI with the apiKey in an object and remove unnecessary type casting.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function generateOrthographicView(
  base64Image: string,
  mimeType: string,
  aspectRatio: AspectRatio
): Promise<string> {
  const prompt = `
    You are a 3D rendering assistant. The user has provided an image of an object.
    Your task is to:
    1. Analyze the input image, which could be a photograph, sketch, blueprint, or model sheet.
    2. Infer the object's 3D structure, including depth, volume, and any unseen details. If multiple views are provided in a single image, merge them into a coherent 3D representation.
    3. Generate a new, high-resolution image of the object rendered as a 3D orthographic projection.
    4. The final image MUST have a pure white background (#FFFFFF).
    5. The object should be centered in the frame.
    6. Preserve the original textures and colors of the object.
    7. Add subtle, soft shadows to enhance the sense of depth and form.
    8. The output image MUST have an aspect ratio of ${aspectRatio}.
    Ensure the output is a clean, sharp, and professional-looking rendering suitable for use in 3D modeling pipelines.
  `;

  const imagePart = {
    inlineData: {
      data: base64Image,
      mimeType: mimeType,
    },
  };

  const textPart = {
    text: prompt,
  };

  // FIX: Use ai.models.generateContent and pass the model name directly, instead of pre-defining the model. This follows the recommended API usage pattern.
  const response: GenerateContentResponse = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [imagePart, textPart],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });
  
  // FIX: More robustly parse the response to find the generated image data by iterating through parts.
  for (const part of response.candidates?.[0]?.content?.parts ?? []) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image was generated by the API.");
}